num_of_gpus: -1

hparams:
    max_epochs: 50
    batch_size: 28
    lr: 0.0015
    accumulate_grad_batches: 5
    gradient_clip_val: 0.5
    lin1_size: 512
    lin2_size: 256
    output_size: 38
    weight_decay: 0.00005

resume:
    resume_from_ckpt: True
    wandb_run_id: resumedRun2
    ckpt_path: "epoch=25.ckpt"

loggers:
    wandb:
        project: "skyhacks2020"
        team: "kino"
        group: None
        job_type: "train"
        tags: []
        log_model: False

callbacks:
    checkpoint:
        monitor: "val_f1_score"
        save_top_k: 1
        save_last: True
        mode: "max"
    early_stop:
        monitor: "val_f1_score"
        patience: 6
        mode: "max"

printing:
    progress_bar_refresh_rate: 5
    weights_summary: "top"
    profiler: False
