FROM python:3.8
EXPOSE 8501
WORKDIR /app
ENV PYTHONPATH "/app"
COPY requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt
RUN pip3 install streamlit
RUN apt-get update
RUN apt-get install 'ffmpeg' 'libsm6' 'libxext6' -y
RUN python3 -m spacy download pl_core_news_sm
RUN python3 -m nltk.downloader popular
COPY . .
CMD streamlit run ./streamlit_app/app.py
